name: Node Release
run-name: Node Release [${{ github.ref_name }}] triggered by [${{ github.event_name }}/${{ github.actor }}]

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  release:
    uses: krauters/shared-workflows/.github/workflows/node-release.yaml@main
    secrets:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
